version: '3.7'
services:
  freeipa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freeipa-server
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    environment:
      - IPA_SERVER_IP=192.168.211.194  # Cambiar por tu IP
      - PASSWORD=Angel123*   # Cambiar contraseña
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /storage:/storage
      - /var/log/iptables:/var/log/iptables